Install ai operator
redhat-ztp/ztp-cluster-deploy pull request #106
Opened 2021-04-28 09:24 UTC by yrobla

2021-04-30 13:01 UTC, serngawy commented on install-ai-operator/inventory/hosts.sample
> +device_paths=[ '/dev/vda', '/dev/vdb' ]
can we use kcli to create the dist instead of let the user create it first ? may I'm missing something

2021-04-30 14:17 UTC, yrobla commented on install-ai-operator/inventory/hosts.sample
> +device_paths=[ '/dev/vda', '/dev/vdb' ]
kcli is creating the disks. This is actually for specifying the disks in the localvolume template. So we give freedom for users with his own cluster, to specify the disks in the format they have.

2021-05-03 15:18 UTC, serngawy requested changes

2021-05-03 15:18 UTC, serngawy commented on install-ai-operator/roles/prepare-environment/tasks/main.yml
> +  when: provisioner_cluster_name is defined and provisioner_cluster_name|length > 0
I believe you should check here for the provisioner_cluster_kubeconfig AND in the readme you may explain that the user should add the provisioner_cluster_name either ways as it is re-used with other tasks such as mirror-ai-images ?

2021-05-03 15:18 UTC, serngawy commented on install-ai-operator/README.md
> +path of an already provisioned cluster.
the user should add the provisioner_cluster_name either ways as it is re-used with other tasks such as mirror-ai-images

2021-05-03 15:22 UTC, yrobla commented on install-ai-operator/roles/prepare-environment/tasks/main.yml
> +  when: provisioner_cluster_name is defined and provisioner_cluster_name|length > 0
The aim is to just install a provisioner cluster if we give the name and the domain. If the user doesn't give any cluster name/domain, I assume that the cluster is provisioned by the user itself.
In that case it's just enough to provide the KUBECONFIG file, so we can perform install operations on an already provisioned cluster.

2021-05-04 12:16 UTC, serngawy approved these changes

2021-05-04 12:37 UTC, merged