Extend flexibility of cluster parameters
redhat-ztp/ztp-cluster-deploy pull request #126
Opened 2021-06-04 21:31 UTC by imiller0

Convert nmstate to template with basic networking parameters supplied in
inventory file. Allow flexibility in providing cluster networking info
(allow defaults for some networking). Additional documentation in
inventory file.

Signed-off-by: Ian Miller <imiller@redhat.com>

2021-06-04 21:32 UTC, imiller0 commented
/assign yrobla

2021-06-08 14:45 UTC, yrobla requested changes
So i think it's a good idea, but i would also let the freedom of writing your own nmstate file. That's because what is shown there, is just a sample, but nmstate can have multiple formats. You can have ipv6 config (in another pr), you may want to add vlan/bonding... so many cases to just reflect on a template.
Can we find some solution to generate a simple template, but also leave freedom to configure whatever is needed?

2021-06-10 13:27 UTC, serngawy commented
Just to clarify Yalonda comment. If I have my nnmstate file and set the nmstate_path= to it and ignore other parameters. Does it will just pickup my nmstate file ?

2021-06-10 17:09 UTC, lack commented on create-cluster-sno/roles/chrony_day0/tasks/main.yml
> +- name: Create the workload-partitioning MachineConfig manifest
This name doesn't match the action ;)

2021-06-10 17:09 UTC, imiller0 commented
Yes, the nmstate_path variable controls what file is pulled in. The main change I made was to treat it as a template so Ansible will do the substitutions. I think this allows the flexibility @yrobla is looking for along with some scalability by allowing the values to come from the inventory.

2021-06-10 17:12 UTC, imiller0 commented on create-cluster-sno/roles/chrony_day0/tasks/main.yml
> +- name: Create the workload-partitioning MachineConfig manifest
Fixed :)

2021-06-10 18:13 UTC, serngawy approved these changes

2021-06-11 05:28 UTC, yrobla approved these changes

2021-06-11 05:30 UTC, merged