fix for airgap and supermicro
redhat-ztp/ztp-cluster-deploy pull request #136
Opened 2021-07-02 09:44 UTC by pmallan

2021-07-02 09:49 UTC, pmallan commented
@yrobla Please review the changes and let me know for any changes. We have tested the changes in our environment and worked fine.

2021-07-12 09:53 UTC, yrobla requested changes

2021-07-12 09:53 UTC, yrobla commented on common-roles/enroll-supermicro/tasks/main.yml
> -    url: "https://{{ bmc_address }}/redfish/v1/Managers/1/VM1/CfgCD/Actions/IsoConfig.UnMount"
I think that you better add a new enroll-supermicro-new playbook, with the new API. If i add that to the playbook, i will break the old supermicros using the older api.

2021-07-12 10:36 UTC, pmallan commented on common-roles/enroll-supermicro/tasks/main.yml
> -    url: "https://{{ bmc_address }}/redfish/v1/Managers/1/VM1/CfgCD/Actions/IsoConfig.UnMount"
Hi @yrobla as you see I created enroll-supermicro-old and it has original playbooks and this will work for older supermicros. The "enroll-supermicro" has updated code which will work for newer supermicros. I did this change so that we can avoid changing invocation playbooks. Also avoid changing variables in inventory file. 
In our automation, the server type is set to "SuperMicro" and this value is used invoke specific playbooks. If we add server type as "SuperMicroNew" then it looks odd.

2021-07-15 07:35 UTC, merged