deploying sno documentation added along with modified .yaml file under inventory
redhat-ztp/ztp-cluster-deploy pull request #169
Opened 2021-10-07 15:39 UTC by sabbir-47

Documentation update

2021-10-08 05:33 UTC, yrobla requested changes

2021-10-08 05:33 UTC, yrobla commented on create-cluster-acm/README.md
> +## Deploying SNO on Sopke cluster
nit, spoke

2021-10-08 05:33 UTC, yrobla commented on create-cluster-acm/README.md
> +    TASK TAGS: [add-extra-workers, create-extra-partition, create-vms, deploy-cluster-with-policy, generate-manifests, install-requirements, mirror-release-image]
can you mention those in order, and explain the meaning of each one? Also mention that you can run tags step by step using --tags=xxx. This is useful when people want just to execute an specific step, or retry something that is failing

2021-10-08 05:33 UTC, yrobla commented on create-cluster-acm/README.md
> +you can launch the playbook to provision a spoke cluster with skipping add--extra-workers for deploying SNO as:
actually no need to skip those anymore. If you deploy SNO, as it is not detecting worker_vms, it is not executing it.

2021-10-08 14:14 UTC, sabbir-47 commented on create-cluster-acm/README.md
> +## Deploying SNO on Sopke cluster
fixed

2021-10-08 14:14 UTC, sabbir-47 commented on create-cluster-acm/README.md
> +    TASK TAGS: [add-extra-workers, create-extra-partition, create-vms, deploy-cluster-with-policy, generate-manifests, install-requirements, mirror-release-image]
added

2021-10-08 14:14 UTC, sabbir-47 commented on create-cluster-acm/README.md
> +you can launch the playbook to provision a spoke cluster with skipping add--extra-workers for deploying SNO as:
fixed

2021-10-08 14:35 UTC, yrobla requested changes

2021-10-08 14:35 UTC, yrobla commented on create-cluster-acm/README.md
> +* install-requirements role consists of building policygenrator and installing few packages including sushy-tools
nit, policygenerator

2021-10-08 14:35 UTC, yrobla commented on create-cluster-acm/README.md
> +    ansible-playbook -i inventory/hosts.sno.yaml.sample playbook.yml
Ok, the proper way is:
- copy hosts.sno.yaml.sample to hosts.sno.yaml and customize with your values
- run ansible-playbook -i inventory/hosts.sno.yaml playbook.yml

2021-10-08 14:35 UTC, yrobla commented on create-cluster-acm/README.md
> +You can use **hosts.yaml.sample** file under /inventory to create 3 node clusters, the available tags are the same as mentioned above. For **Day 2** operations, you can use the **hosts.extraworkers.y
Please add 2 different new sections there:
- deploy 3-node clusters with additional workers -> you can mention the sample of 5nodes, explain that the vms need to have master/worker roles
- add additional workers on day 2 -> explain that you need to deploy standard cluster, and wait until the clusters is completely deployed and imported into ACM. Then explain that you need to run the playbook with hosts.extraworkersyaml.sample, and just limiting to the add-workers tag: ansible-playbook -i inventory/hosts.extraworkers.yaml --tags=add_extra_workers

2021-10-08 15:00 UTC, sabbir-47 commented on create-cluster-acm/README.md
> +* install-requirements role consists of building policygenrator and installing few packages including sushy-tools
fixed

2021-10-08 15:00 UTC, sabbir-47 commented on create-cluster-acm/README.md
> +    ansible-playbook -i inventory/hosts.sno.yaml.sample playbook.yml
done

2021-10-08 15:00 UTC, sabbir-47 commented on create-cluster-acm/README.md
> +You can use **hosts.yaml.sample** file under /inventory to create 3 node clusters, the available tags are the same as mentioned above. For **Day 2** operations, you can use the **hosts.extraworkers.y
created

2021-10-11 09:07 UTC, yrobla approved these changes

2021-10-11 09:07 UTC, merged