(WIP) Update ACM-spoke playbook with ztp-acm-manifest
redhat-ztp/ztp-cluster-deploy pull request #31
Opened 2021-01-29 02:33 UTC by serngawy

Signed-off-by: melserngawy <melserng@redhat.com>

2021-02-01 09:52 UTC, yrobla requested changes

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/README.md
> +    - We assume that there is already ACM hub up and running. If not you can use the ../acm-hub/playbook.yaml to create ACM hub.
Can you mention that is very important to have this manifest applied? https://github.com/redhat-ztp/ztp-acm-manifests/blob/main/hub/04_add_subscription_permission.yaml
If you bring your ACM manually, you need to apply this config file , to give proper permissions, otherwise the subscriptions are not created correctly.

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/README.md
> +This playbook for spoke-clusters to join the ACM hub.
is to allow

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/README.md
> +    - We assume that there is already ACM hub up and running. If not you can use the ../acm-hub/playbook.yaml to create ACM hub.
already an ACM hub... If not, you can use ... to create the ACM hub

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/README.md
> +        - Note: ACM hub shouldn't be created on one of the spoke-clusters.
The ACM hub needs an independent cluster to run, spoke clusters cannot be reused for that.

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/README.md
> +    - The clusters that will be defiend in the inventroy/hosts under [clusters] section should have its profiles in the ztp-acm-manifest. Check the https://github.com/redhat-ztp/ztp-acm-manifests for
be defined ... inventory/hosts

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/README.md
> +    - The clusters that will be defiend in the inventroy/hosts under [clusters] section should have its profiles in the ztp-acm-manifest. Check the https://github.com/redhat-ztp/ztp-acm-manifests for
Can you link to the exact folder of ztp-acm-manifest link/folder ?

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/README.md
> +    3- make a copy inventory/hosts.sample file and name it hosts under same directory.
of the ... file and rename it with the `hosts` name under the same directory

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/import_cluster.sh
> +cat << EOF > ./$CLUSTER_NAME.yaml
i think that for the moment is ok... but i have been thinking in relying on kustomize for that. It needs some work in the ztp-acm-manifests folder, maybe as a follow up

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/inventory/hosts.sample
> +# Cluster name and profil should be defined at the ACM manifest repo
profile

2021-02-01 09:52 UTC, yrobla commented on acm-spoke/inventory/hosts.sample
> +localhost ansible_connection=local
maybe add an entry here for a remote provisioner as well, as we have in the remote worker playbook

2021-02-01 15:22 UTC, serngawy commented on acm-spoke/README.md
> +    - We assume that there is already ACM hub up and running. If not you can use the ../acm-hub/playbook.yaml to create ACM hub.
I was thinking this should be explained and written in the ztp-acm-manifest

2021-02-01 15:22 UTC, serngawy commented on acm-spoke/import_cluster.sh
> +cat << EOF > ./$CLUSTER_NAME.yaml
in fact, this script should be under ztp-ran-manifest/spoke_clusters

2021-02-02 10:09 UTC, yrobla reviewed
just small typo missing, thx!

2021-02-02 10:09 UTC, yrobla commented on acm-spoke/README.md
> +    - The clusters that will be defined in the inventroy/hosts under [clusters] section should have its profiles in the ztp-acm-manifest. Check the https://github.com/redhat-ztp/ztp-acm-manifests/tre
inventory/hosts

2021-02-02 15:10 UTC, yrobla approved these changes

2021-02-02 15:10 UTC, merged