Fix item.name in the enroll-cluster tasks and execute import-cluster script
redhat-ztp/ztp-cluster-deploy pull request #44
Opened 2021-02-04 01:03 UTC by serngawy

2021-02-04 11:39 UTC, yrobla requested changes

2021-02-04 11:39 UTC, yrobla commented on acm-spoke/inventory/hosts.sample
> +out_dir=/tmp
can you reuse the temporary_path entry, that already exists on the inventory?

2021-02-04 14:23 UTC, serngawy commented on acm-spoke/inventory/hosts.sample
> +out_dir=/tmp
there is no temporary_path entry already exist

2021-02-04 16:32 UTC, yrobla commented on acm-spoke/enroll-clusters.yaml
> +  shell: "oc get secret/{{ hostvars[item].name }}-cluster-import -n {{ hostvars[item].name }} -o jsonpath={.data.crds\\\\.yaml} | base64 --decode > {{ acm_directory.path }}/crd.yaml"
why are you adding the -cluster here? shouldn't that just be the name of the cluster as before?

2021-02-04 16:39 UTC, serngawy commented on acm-spoke/enroll-clusters.yaml
> +  shell: "oc get secret/{{ hostvars[item].name }}-cluster-import -n {{ hostvars[item].name }} -o jsonpath={.data.crds\\\\.yaml} | base64 --decode > {{ acm_directory.path }}/crd.yaml"
Actually it wasn't working, the name of the cluster in ran manifest having "cluster"
https://github.com/redhat-ztp/ztp-ran-manifests/blob/main/spoke_clusters/01_sample_cu_cluster.yaml#L14

2021-02-08 08:49 UTC, yrobla approved these changes

2021-02-09 07:35 UTC, closed without merging