Remove repeated step in prepare env task, Update readme and variable description
redhat-ztp/ztp-cluster-deploy pull request #7
Opened 2020-12-15 02:08 UTC by serngawy

2020-12-15 08:18 UTC, yrobla requested changes
Thanks for that! I just added some minor comments.

2020-12-15 08:18 UTC, yrobla commented on ai-deploy-cluster-remoteworker/README.md
> +        $ sudo ansible-playbook playbook.yml -vvv -i inventory/hosts --tags=prepare-envitronment
typo: environment

2020-12-15 08:18 UTC, yrobla commented on ai-deploy-cluster-remoteworker/README.md
> +    6- Make sure that AI pod has been created and the http server is running
I think that the sentence need some context: I would mention that you need to have "something" serving files , for the ignition/rootfs... it can be httpd, nginx, python... just mention that you need to have a directory in your server where to store the content, and then serve files from there with http protocol

2020-12-15 08:18 UTC, yrobla commented on ai-deploy-cluster-remoteworker/README.md
> +    7- Based on your env and your machine intf us nmcli command to set the network-config under /opt/ dir
use

2020-12-15 08:18 UTC, yrobla commented on ai-deploy-cluster-remoteworker/README.md
> +        $ sudo ansible-playbook playbook.yml -vvv -i inventory/hosts --skip-tags=prepare-envitronment
typo, environment

2020-12-15 08:18 UTC, yrobla commented on ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml
> +- name: install httpd
can you make it optional? it may be that people have some httpd already running, or that want to use another server. You can control it with some var in inventory

2020-12-15 16:53 UTC, serngawy commented on ai-deploy-cluster-remoteworker/roles/prepare-environment/tasks/main.yml
> +- name: install httpd
I prefer to keep it by default as we need it in our lab env. If someone know what he is doing he can disable that and use his own env setup.

2020-12-16 23:51 UTC, dshchedr commented on ai-deploy-cluster-remoteworker/README.md
> +        - Ansibale modules: community.libvirt, containers.podman and containers.general
here is a typo - ` containers.general -> community.general`

2020-12-16 23:56 UTC, dshchedr commented on ai-deploy-cluster-remoteworker/README.md
> +        - Ansibale modules: community.libvirt, containers.podman and containers.general
and also `Ansibale -> Ansible`

2020-12-17 08:25 UTC, yrobla requested changes

2020-12-17 08:25 UTC, yrobla commented on ai-deploy-cluster-remoteworker/README.md
> +    2- go to ai-deploly-cluster-remoteworker dir
deploy

2020-12-17 08:25 UTC, yrobla commented on ai-deploy-cluster-remoteworker/inventory/hosts.sample
> +# Make sure api_vip is mapped in your env DNS server to api.{cluster_name}.{cluster_domain} AND ingress_vip to apps.{cluster_name}.{cluster_domain}
.apps ... it's a wildcard

2020-12-22 18:42 UTC, dshchedr commented on ai-deploy-cluster-remoteworker/inventory/hosts.sample
> +ignition_url=http://192.168.112.199/ignition_config
I'm not very familiar with it, may be the port should be 8080? 

`ignition_url=http://192.168.112.199/ignition_config`

2020-12-22 19:49 UTC, yuvalk commented on ai-deploy-cluster-remoteworker/inventory/hosts.sample
> +ignition_url=http://192.168.112.199/ignition_config
nope
so `ai_url` is the url to the ai service, typically running on 8080, especially if deployed with this playbook.
`ignition_url` is the url to the ignition file. the file itself is produced by the playbook and stored in the right location the url is consumed by the iso to get to that ignition file. so you need a httpd server and copy the file to the right location.

2021-01-04 11:36 UTC, yrobla approved these changes

2021-01-04 11:36 UTC, merged